//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public string MemberNumber { get; set; }
        public string MemberIdentifier { get; set; }
        public Nullable<int> BirthDate { get; set; }
        public Nullable<int> SSN { get; set; }
    }
}
